services:
  nginx:
    image: nginx:latest
    container_name: hosting_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

  php74:
    build: ./cgi/php/php74
    container_name: php74
    volumes:
      - /var/www:/var/www
      - /etc/php74/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - /etc/php74/fpm/zzzz-custom.conf:/usr/local/etc/php-fpm.d/zzzz-custom.conf
    expose:
      - "9000"

  php80:
    build: ./cgi/php/php80
    container_name: php80
    volumes:
      - /var/www:/var/www
      - /etc/php80/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - /etc/php80/fpm/zzzz-custom.conf:/usr/local/etc/php-fpm.d/zzzz-custom.conf
    expose:
      - "9000"

  php81:
    build: ./cgi/php/php81
    container_name: php81
    volumes:
      - /var/www:/var/www
      - /etc/php81/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - /etc/php81/fpm/zzzz-custom.conf:/usr/local/etc/php-fpm.d/zzzz-custom.conf
    expose:
      - "9000"

  php82:
    build: ./cgi/php/php82
    container_name: php82
    volumes:
      - /var/www:/var/www
      - /etc/php82/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - /etc/php82/fpm/zzzz-custom.conf:/usr/local/etc/php-fpm.d/zzzz-custom.conf
    expose:
      - "9000"

networks:
  default:
    external: true
    name: hosting_net


# Make the directories:
# mkdir -p /etc/php74/fpm
# mkdir -p /etc/php80/fpm
# mkdir -p /etc/php81/fpm
# mkdir -p /etc/php82/fpm
# mkdir -p /etc/php82/ini/
# mkdir -p /etc/php81/ini/
# mkdir -p /etc/php80/ini/
# mkdir -p /etc/php74/ini/

# Create the files
# touch /etc/php74/ini/custom.ini
# touch /etc/php80/ini/custom.ini 
# touch /etc/php81/ini/custom.ini
# touch /etc/php82/ini/custom.ini
# touch /etc/php74/fpm/www.conf
# touch /etc/php80/fpm/www.conf   
# touch /etc/php81/fpm/www.conf
# touch /etc/php82/fpm/www.conf