services:
  nginx:
    image: nginx:latest
    container_name: hosting_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

  php74:
    build: ./php74
    container_name: php74
    volumes:
      - /var/www:/var/www
    expose:
      - "9000"

  php80:
    build: ./php80
    container_name: php80
    volumes:
      - /var/www:/var/www
    expose:
      - "9000"

  php81:
    build: ./php81
    container_name: php81
    volumes:
      - /var/www:/var/www
    expose:
      - "9000"

  php82:
    build: ./php82
    container_name: php82
    volumes:
      - /var/www:/var/www
    expose:
      - "9000"

networks:
  default:
    external: true
    name: hosting_net